export const STATISTICS_SEND_REQUEST = "STATISTICS_SEND_REQUEST";
export const STATISTICS_SUCCESS_REQUEST = "STATISTICS_SUCCESS_REQUEST";
export const STATISTICS_FAILED_REQUEST = "STATISTICS_FAILED_REQUEST";